apiVersion: v1
kind: Service
metadata:
  name: configreader-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    run: configreader
  sessionAffinity: None
  type: LoadBalancer


