apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: configreader
  name: configreader
  namespace: default
spec:
  progressDeadlineSeconds: 420
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: configreader
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: configreader
    spec:
      containers:
        - image: tclark/configreader
          imagePullPolicy: Always
          name: configreader
          resources: 
            requests:
              cpu: "10m"
              memory: "64Mi"
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: secret
          envFrom:
          - configMapRef:
              name: configs
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always


